### ISSUE TITLE
How can I populate a property in a sub-document ?

### ISSUE THREAD

**Issue by jokerrider007** [loris/api-query-params#111]
Can i get populate query parameter like this { path: 'array.objectProperty' } but when i send populate param `?populate=array.objectProperty`. The populate  that I received was multi-levels populate object.

**Comment by dachia** [comment]
bump

**Comment by loris** [comment]
I'm not using mongoose populate feature myself, so i'm not really sure what you are looking for. Right now, implementation (implemented by someone else as a PR) is the following regarding populated props with dot notation :

```
  const res = aqp('populate=a,a.a1,a.a1.a2');
  t.truthy(res);
  t.deepEqual(res.population, [
    {
      path: 'a',
      populate: {
        path: 'a1',
        populate: {
          path: 'a2',
        },
      },
    },
  ]);
```

My understanding is that you'd like something like that instead `{ path: 'a.a1.a2' }` right?
The library currently has no way to do that because it would requires visibility over your Mongoose schema (ie, is `a1` a schema or just a property of `a`). Wouldn't it be easier to be implemented in your code? You can still use aqp to get the object, and then you transform the `population` property based on your schema.

**Comment by dachia** [comment]
Yeah, that makes a lot of sense. Thanks!
