### ISSUE TITLE
Provide as commonjs module 

### ISSUE THREAD

**Issue by StarpTech** [loris/api-query-params#82]
Hi, would be nice if you could transpile it with Babel so require and import can work in the same way. The import syntax is not supported in nodejs. Thanks.

**Comment by StarpTech** [comment]
At the moment I have to call `aqp.default(query)`

**Comment by StarpTech** [comment]
It seems that you already do it but it's not published on NPM.

**Comment by loris** [comment]
Hi @StarpTech, I'm not so sure what is the issue.
Currently `api-query-params` is properly transpiled by babel with the `es2015` preset (which do contain plugins to allow both require/import module loading) and the resulting file is outputed in `dist/index.js` which is the one published on NPM.

I just `npm install api-query-params` on an empty folder, and the `dist/index.js` file do contain stuff like `function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`

**Comment by loris** [comment]
It looks like I would need to replace `export default ...` with `module.exports = ...;` in the lib file to allow `var aqp = require('api-query-params');` to work directly. Not sure if this is the proper way to support both `import`/`require` and it looks like I would need to publish it in a `@5.0.0` version since it breaks code currently using `aqp.default`

**Comment by loris** [comment]
Closed by https://github.com/loris/api-query-params/pull/83
