### ISSUE TITLE
Exclude key=""

### ISSUE THREAD

**Issue by lapidus** [loris/api-query-params#92]
Really nice lib!

The only thing I'm having trouble figure out is how to exclude "" values:

```
{
 id: 23423,
 key1 : "test",
 key2 : "" 
}

```

I tried &key2!="" with no effect. 

Thanks!

**Comment by loris** [comment]
Hi @lapidus 
Filtering on existing, but empty values are indeed not possible at the moment.
One workaround is to use the `filter` param which give you access to more advanced mongo operations, for instance `key1=test&filter={"key2":{"$ne":""}}` would work.

I was considering changing the way "exists" / "do not exists" operators work in the lib:
Instead of mapping exactly the $exists mongodb operator (ie, `&foo` would translate to `{ foo: { $exists: true }}` and `&!bar` would translate to `{ bar: { $exists: false }}`, I was considering adding test to check if the values are null or empty too: ie `&foo` would translate to `{ foo: { $exists: true, $nin: [null, '', []]}}`. This would be a breaking change tho, so next major version.

**Comment by lapidus** [comment]
Thank you!

**Comment by Mangosteen-Yang** [comment]
@loris Thank you very much for providing this awesome tool.
How is the $exists changing going?
